services:
    fastapi:
        build: .
        container_name: fastapi_app
        env_file: .env
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        networks: 
            - nginx_proxy
networks: 
    nginx_proxy:
        external: true
        
